service: pruebas-scheduler

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  profile: pruebas
  timeout: 30 # API Gateway is limited to 30 seconds
  region: ${opt:region, 'us-west-2'}
  stage: ${opt:stage, 'qa'}
  deploymentBucket:
    name: pruebas-scheduler-123
functions:
  prueba:
    handler: src/handlers/prueba.handler
    events:
      - http:
          path: /prueba
          method: post
  mailer:
    handler: src/handlers/mailer.handler
   
package:
  excludeDevDependencies: true
  exclude:
    - .env.*
    - git_key
    - node_modules/**
